language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- pypy
install:
- pip install pytest==2.7.3
- pip install Cython
- pip install -r requirements.txt
script:
- py.test -v
deploy:
  provider: pypi
  user: hroncok
  password:
    secure: TS2gTwXyPWQYGh0TuU1xxPvU9XGB/M3JB1wP5oDqwsSfhMZXKX8S2KNhul/0yKUbWTHgld865wmcHqnfEIwGJ2OFsTX3FdZy2P31UveC66chx+RedI069SDgsfpaHsF0Gg9ZgutaMlOxkS2EInbdeaTM7q/AKzA89fnVLqZgR/U=
  on:
    tags: true
    repo: ctu-yfsg/2015-f-citygml
